name: YouTube Live Chat Bot

on:
  schedule:
   - cron: "0 4 * * 0" //Every Sunday at 9:30AM IST (4:00 AM UTC)

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Decode credentials
    run: |
      echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 --decode > credentials.json

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.11"

  - name: Install dependencies
    run: pip install -r requirements.txt

  - name: Run bot
    run: python live_chat_bot.py
